#!/usr/bin/env bash
#
# The panel side of the test bench.
#
# Four suites - integration, loyalty (its server half), zincir and geri - are
# about the contract between the restaurant PC and pos.noktapp.com, so they
# cannot be proved with the PC alone. This script builds the other end of that
# contract locally: the panel schema, one test tenant (client 19, the same id
# every local suite uses), an active licence, and the shared guest registry the
# sadakat lookup reads.
#
# It creates NOTHING that resembles a live account: the tenant is
# restoran@ornek.com with a password that is written in this file and in
# test/integration.js, and both databases are dropped and rebuilt on every run.
# Point it at a real panel database and you will lose that database - it is a
# sandbox fixture and nothing else.
#
#   test/panel-fixture.sh            build the databases
#   test/panel-fixture.sh --serve    build them and start the php workers too
#
# Environment (defaults are the sandbox's):
#   DB_PORT 3399   DB_USER noktapp   DB_PASS nokpass
#   PANEL_DB nokpos_panel   SHARED_DB nokpos_shared
set -u
HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
DB_PORT="${DB_PORT:-3399}"; DB_USER="${DB_USER:-noktapp}"; DB_PASS="${DB_PASS:-nokpass}"
PANEL_DB="${PANEL_DB:-nokpos_panel}"; SHARED_DB="${SHARED_DB:-nokpos_shared}"
M="mysql --port=$DB_PORT --protocol=tcp -u$DB_USER -p$DB_PASS"

echo "Rebuilding $PANEL_DB…"
$M -e "DROP DATABASE IF EXISTS \`$PANEL_DB\`; CREATE DATABASE \`$PANEL_DB\` CHARACTER SET utf8mb4" || exit 1
# the same order setup.php uses, because later files reference earlier tables
for f in panel_schema chain_schema rapor_schema panel_ops_schema bayi_schema para_schema teshis_schema uyari_schema; do
  $M "$PANEL_DB" < "$ROOT/panel/sql/$f.sql" || exit 1
done

# The tenant every local suite logs in as. The hash is generated by PHP itself
# rather than pasted, so it matches whatever algorithm this PHP defaults to.
HASH="$(php -r 'echo password_hash("Restoran1234", PASSWORD_DEFAULT);')"
# The panel's own PHP suites (panel/tests/*.php) sign in as an administrator;
# these are the defaults those suites use. They exist ONLY in this throwaway
# database, which is dropped and rebuilt every time this script runs, and are
# not a credential for anything real.
ADMINHASH="$(php -r 'echo password_hash("ChainTest123", PASSWORD_DEFAULT);')"
$M "$PANEL_DB" <<SQL || exit 1
INSERT INTO np_tenants (id, code, company_name, owner_name, email, password_hash, phone, city, is_active)
VALUES (19, 'TEST19', 'Ornek Restoran', 'Test Sahibi', 'restoran@ornek.com', '$HASH', '02120000000', 'Istanbul', 1);
INSERT INTO np_licences (tenant_id, licence_key, plan, status, seats, features, starts_at, expires_at, grace_days)
VALUES (19, 'TEST-0000-0000-0019', 'standart', 'active', 5,
        '["paket","sadakat","okc","zincir"]', CURDATE(), DATE_ADD(NOW(), INTERVAL 1 YEAR), 30);
INSERT INTO np_admins (email, name, password_hash, is_active)
VALUES ('erik@noktapp.com', 'Test Yonetici', '$ADMINHASH', 1);
-- size_bytes and sha512 are filled in because /indir/latest.yml.php refuses to
-- publish a feed it cannot complete, and rightly: a row marked current with no
-- installer behind it is what made every till log a checksum error for a week.
-- The fixture has no .exe on disk, so it carries the numbers itself.
INSERT INTO np_versions (version, channel, filename, size_bytes, sha512, release_notes, is_current)
VALUES ('3.6.2', 'stable', 'NoktAppPOS-Setup-3.6.2.exe', 1024,
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==',
        'Test surumu', 1);
SQL

# The chain tenant test/zincir.js works against: head office (22) with two
# branches, and the second till (23) that must never see the first one's
# exceptions. The licence key is the one zincir.js caches locally, and the
# master menu is the documented starting point - Kofte 180.00 with its price
# locked, Cay 20.00 without. The suite republishes and resets this on every
# run; what it cannot do is invent the tenant, which is why it is here.
$M "$PANEL_DB" <<SQL || exit 1
INSERT INTO np_tenants (id, code, company_name, owner_name, email, password_hash, city, is_active)
VALUES (22, 'ZINCIR22', 'Zincir Demo', 'Zincir Sahibi', 'zincir@ornek.com', '$HASH', 'Istanbul', 1),
       (23, 'ZINCIR23', 'Zincir Demo Kaleici', 'Zincir Sahibi', 'kaleici@ornek.com', '$HASH', 'Antalya', 1);
INSERT INTO np_licences (tenant_id, licence_key, plan, status, seats, features, starts_at, expires_at, grace_days)
VALUES (22, '13104EA0EEB3F4CBB703BEE8', 'zincir', 'active', 10,
        '["paket","sadakat","okc","zincir"]', CURDATE(), DATE_ADD(NOW(), INTERVAL 1 YEAR), 30);
INSERT INTO np_branches (tenant_id, code, name, city, is_active)
VALUES (22, 'MERKEZ', 'Merkez', 'Istanbul', 1),
       (22, 'KALEICI', 'Kaleici', 'Antalya', 1);
INSERT INTO np_menu_categories (tenant_id, master_code, name, sort_order, is_active, price_locked)
VALUES (22, 'YEMEKLER', 'Yemekler', 1, 1, 1),
       (22, 'ICECEKLER', 'Icecekler', 2, 1, 0);
INSERT INTO np_menu_products (tenant_id, master_code, category_id, name, price, vat_rate, sort_order, is_active, price_locked)
VALUES (22, 'KOFTE', (SELECT id FROM np_menu_categories WHERE tenant_id=22 AND master_code='YEMEKLER'),
        'Kofte', 180.00, 10.00, 1, 1, 1),
       (22, 'CAY', (SELECT id FROM np_menu_categories WHERE tenant_id=22 AND master_code='ICECEKLER'),
        'Cay', 20.00, 10.00, 2, 1, 0);
SQL

# The shared guest registry: the tables pass.noktapp.com owns, taken from
# the product schema itself so the fixture cannot drift from the real shape.
echo "Rebuilding $SHARED_DB…"
$M -e "DROP DATABASE IF EXISTS \`$SHARED_DB\`; CREATE DATABASE \`$SHARED_DB\` CHARACTER SET utf8mb4" || exit 1
php -r '
$src = file_get_contents($argv[1]) . file_get_contents($argv[2]);
foreach (["customers", "loyalty_qr_tokens", "loyalty_cards", "loyalty_programs"] as $t) {
    if (preg_match("/CREATE TABLE `{$t}` \(.*?\) ENGINE[^;]*;/s", $src, $m)) echo $m[0], "\n";
    if (preg_match("/ALTER TABLE `{$t}`\s+ADD PRIMARY KEY[^;]*;/s", $src, $m)) echo $m[0], "\n";
    if (preg_match("/ALTER TABLE `{$t}`\s+MODIFY[^;]*;/s", $src, $m)) echo $m[0], "\n";
    foreach (["ADD UNIQUE KEY", "ADD KEY"] as $k) {
        if (preg_match("/ALTER TABLE `{$t}`\s+{$k}[^;]*;/s", $src, $m)) echo $m[0], "\n";
    }
}' "$ROOT/database/01_schema_core.sql" "$ROOT/database/05_loyalty.sql" | $M "$SHARED_DB" || exit 1

echo "panel fixture ready: tenant 19 / restoran@ornek.com"
$M -N -e "SELECT CONCAT('  licence: ', status, ', ', seats, ' seat(s), expires ', expires_at) FROM $PANEL_DB.np_licences WHERE tenant_id=19"
$M -N -e "SELECT CONCAT('  registry tables: ', GROUP_CONCAT(table_name)) FROM information_schema.tables WHERE table_schema='$SHARED_DB'"

[ "${1:-}" = "--serve" ] || exit 0

# The panel served the way test/README.md describes: PHP's dev server is single
# threaded and the relay holds a request open, so one worker would deadlock
# against itself. Four workers behind the round-robin proxy on 8090.
export NP_DB_HOST=127.0.0.1 NP_DB_PORT="$DB_PORT" NP_DB_NAME="$PANEL_DB" NP_DB_USER="$DB_USER" NP_DB_PASS="$DB_PASS"
export NP_PASS_HOST=127.0.0.1 NP_PASS_PORT="$DB_PORT" NP_PASS_NAME="$SHARED_DB" NP_PASS_USER="$DB_USER" NP_PASS_PASS="$DB_PASS"
pkill -f "php -S 127.0.0.1:80" 2>/dev/null
pkill -f "panel-proxy.js" 2>/dev/null
sleep 1
for p in 8088 8089 8091 8092; do
  ( cd "$ROOT/panel" && setsid php -S 127.0.0.1:$p -t . </dev/null >/tmp/php-$p.log 2>&1 & )
done
sleep 1
setsid node "$HERE/panel-proxy.js" </dev/null >/tmp/panel-proxy.log 2>&1 &
sleep 1
code="$(curl -s -o /dev/null -w '%{http_code}' http://127.0.0.1:8090/)"
echo "  panel on http://127.0.0.1:8090 (HTTP $code)"
